/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const TraitsLazyImport = createFileRoute('/traits')()
const TicketsLazyImport = createFileRoute('/tickets')()
const ThanksLazyImport = createFileRoute('/thanks')()
const SignupLazyImport = createFileRoute('/signup')()
const ProfileLazyImport = createFileRoute('/profile')()
const InspirationLazyImport = createFileRoute('/inspiration')()
const CharacterLazyImport = createFileRoute('/character')()
const AttacksLazyImport = createFileRoute('/attacks')()
const IndexLazyImport = createFileRoute('/')()
const CreateCharacterPage2LazyImport = createFileRoute(
  '/create-character/page2',
)()
const CreateCharacterPage1LazyImport = createFileRoute(
  '/create-character/page1',
)()

// Create/Update Routes

const TraitsLazyRoute = TraitsLazyImport.update({
  path: '/traits',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/traits.lazy').then((d) => d.Route))

const TicketsLazyRoute = TicketsLazyImport.update({
  path: '/tickets',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/tickets.lazy').then((d) => d.Route))

const ThanksLazyRoute = ThanksLazyImport.update({
  path: '/thanks',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/thanks.lazy').then((d) => d.Route))

const SignupLazyRoute = SignupLazyImport.update({
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/signup.lazy').then((d) => d.Route))

const ProfileLazyRoute = ProfileLazyImport.update({
  path: '/profile',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/profile.lazy').then((d) => d.Route))

const InspirationLazyRoute = InspirationLazyImport.update({
  path: '/inspiration',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/inspiration.lazy').then((d) => d.Route))

const CharacterLazyRoute = CharacterLazyImport.update({
  path: '/character',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/character.lazy').then((d) => d.Route))

const AttacksLazyRoute = AttacksLazyImport.update({
  path: '/attacks',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/attacks.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const CreateCharacterPage2LazyRoute = CreateCharacterPage2LazyImport.update({
  path: '/create-character/page2',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/create-character/page2.lazy').then((d) => d.Route),
)

const CreateCharacterPage1LazyRoute = CreateCharacterPage1LazyImport.update({
  path: '/create-character/page1',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/create-character/page1.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/attacks': {
      id: '/attacks'
      path: '/attacks'
      fullPath: '/attacks'
      preLoaderRoute: typeof AttacksLazyImport
      parentRoute: typeof rootRoute
    }
    '/character': {
      id: '/character'
      path: '/character'
      fullPath: '/character'
      preLoaderRoute: typeof CharacterLazyImport
      parentRoute: typeof rootRoute
    }
    '/inspiration': {
      id: '/inspiration'
      path: '/inspiration'
      fullPath: '/inspiration'
      preLoaderRoute: typeof InspirationLazyImport
      parentRoute: typeof rootRoute
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileLazyImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupLazyImport
      parentRoute: typeof rootRoute
    }
    '/thanks': {
      id: '/thanks'
      path: '/thanks'
      fullPath: '/thanks'
      preLoaderRoute: typeof ThanksLazyImport
      parentRoute: typeof rootRoute
    }
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsLazyImport
      parentRoute: typeof rootRoute
    }
    '/traits': {
      id: '/traits'
      path: '/traits'
      fullPath: '/traits'
      preLoaderRoute: typeof TraitsLazyImport
      parentRoute: typeof rootRoute
    }
    '/create-character/page1': {
      id: '/create-character/page1'
      path: '/create-character/page1'
      fullPath: '/create-character/page1'
      preLoaderRoute: typeof CreateCharacterPage1LazyImport
      parentRoute: typeof rootRoute
    }
    '/create-character/page2': {
      id: '/create-character/page2'
      path: '/create-character/page2'
      fullPath: '/create-character/page2'
      preLoaderRoute: typeof CreateCharacterPage2LazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  AttacksLazyRoute,
  CharacterLazyRoute,
  InspirationLazyRoute,
  ProfileLazyRoute,
  SignupLazyRoute,
  ThanksLazyRoute,
  TicketsLazyRoute,
  TraitsLazyRoute,
  CreateCharacterPage1LazyRoute,
  CreateCharacterPage2LazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/attacks",
        "/character",
        "/inspiration",
        "/profile",
        "/signup",
        "/thanks",
        "/tickets",
        "/traits",
        "/create-character/page1",
        "/create-character/page2"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/attacks": {
      "filePath": "attacks.lazy.tsx"
    },
    "/character": {
      "filePath": "character.lazy.tsx"
    },
    "/inspiration": {
      "filePath": "inspiration.lazy.tsx"
    },
    "/profile": {
      "filePath": "profile.lazy.tsx"
    },
    "/signup": {
      "filePath": "signup.lazy.tsx"
    },
    "/thanks": {
      "filePath": "thanks.lazy.tsx"
    },
    "/tickets": {
      "filePath": "tickets.lazy.tsx"
    },
    "/traits": {
      "filePath": "traits.lazy.tsx"
    },
    "/create-character/page1": {
      "filePath": "create-character/page1.lazy.tsx"
    },
    "/create-character/page2": {
      "filePath": "create-character/page2.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
